<?php namespace NorbyBaru\BaseRepoLayer\Tests;

/**
 * Class TestCase
 * @package NorbyBaru\BaseRepoLayer\Tests
 */
abstract class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}